# Generated by Django 5.1.3 on 2024-12-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_post', '0002_postfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
