# Generated by Django 5.1.3 on 2024-12-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_post', '0003_postfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_post',
            field=models.ImageField(blank=True, null=True, upload_to='post_files'),
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
