# Generated by Django 5.1.3 on 2024-12-12 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_friends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagechat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messagechat',
            name='sender',
        ),
        migrations.AddField(
            model_name='messagechat',
            name='friend_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagechat',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
    ]
