# Generated by Django 5.1.3 on 2024-12-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_messagechat_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
