# Generated by Django 5.1.3 on 2024-12-13 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_roomchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchat',
            name='groop',
        ),
        migrations.AddField(
            model_name='roomchat',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='chat.grooprooms'),
        ),
    ]
